### PR TITLE
give a list of items for "ordered" command

### LINKED ISSUE #7: `ordered` should not have a newline after "order"
Screen Shot 2019-07-11 at 8 40 02 AM

### PR DESCRIPTION
**Pull request by the-mikedavis**
Closes #7.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Screen Shot 2019-07-15 at 09 06 30

**Comment by tonyvanriet** [comment]
@the-mikedavis 
this seems to assume that orders are always a single line.
also, the intention was to be able to copy/paste the order command, but you took `order` out of the display. can't say I'm too keen on this PR in its current form.

"for" -> "from", top notch, love it.

**Comment by the-mikedavis** [comment]
ah right i’ve seen @bjornrud do some listicles in his order, should be multi line

I guess there are arguments for keeping the new line after ordered, especially the copy paste. but i’m looking to remove those arguments in #6 @tonyvanriet

**Comment by the-mikedavis** [comment]
Screen Shot 2019-07-16 at 12 00 34 PM

**Pull request merged**
