### PR TITLE
Add a reorder command

### PR DESCRIPTION
**Pull request by the-mikedavis**

### CODE REVIEW

**Comment by the-mikedavis** [comment]
Screen Shot 2019-07-16 at 20 17 37

**Review by tonyvanriet — APPROVED** [review]
solid gold

**Comment by tonyvanriet** [comment]
@the-mikedavis 
thanks for making me look at clojure code again. looks cool.

so, kill #8 and use this?

**Comment by the-mikedavis** [comment]
yeah or merge #8 then merge this. this is branched off #8

**Pull request merged**
